experiment: face68_hourglass
seed: 42

data:
  type: coco_keypoints
  train_json: "C:/Users/simog/hmdrive/head_tracking/mini_pose/datasets/hmd_xreal/annotations/train.json"
  val_json: "C:/Users/simog/hmdrive/head_tracking/mini_pose/datasets/hmd_xreal/annotations/val.json"
  image_root: "C:/Users/simog/hmdrive/head_tracking/mini_pose/datasets/hmd_xreal/images"
  input_size: [512, 512]
  heatmap_size: [128, 128]
  batch_size: 4
  num_workers: 0
  aug:
    use_bbox_crop: true
    face_margin: 0.25
    rotation: 30      # FAN-like rotation
    scale: 0.25       # +/- scale range
    color_jitter: 0.10
    hflip_prob: 0.5

model:
  name: stacked_hourglass
  num_stacks: 4
  num_blocks: 1
  num_feats: 256

loss:
  name: heatmap_mse

train:
  epochs: 60
  lr: 0.00025
  weight_decay: 0.0001
  optimizer: "adam"
  lr_steps: [30, 50]
  lr_gamma: 0.1
  output_dir: "work_dirs/face68_hourglass_fan2d_like"
